---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
  creationTimestamp: null
  name: cmtemplates.cache.spices.dev
spec:
  group: cache.spices.dev
  names:
    kind: CMTemplate
    listKind: CMTemplateList
    plural: cmtemplates
    singular: cmtemplate
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CMTemplate is the Schema for the cmtemplates API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CMTemplateSpec defines the desired state of CMTemplate
            properties:
              template:
                properties:
                  annotationreplace:
                    additionalProperties:
                      type: string
                    type: object
                  cmtemplate:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - annotationreplace
                - cmtemplate
                type: object
            type: object
          status:
            description: CMTemplateStatus defines the observed state of CMTemplate
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
